# Generated by Django 6.0.1 on 2026-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cancellation_public',
            field=models.BooleanField(default=False),
        ),
    ]
